// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// B_basis_eval
arma::vec B_basis_eval(const arma::vec& x, const unsigned int degree, const arma::vec& knots);
RcppExport SEXP _mlabs_B_basis_eval(SEXP xSEXP, SEXP degreeSEXP, SEXP knotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type knots(knotsSEXP);
    rcpp_result_gen = Rcpp::wrap(B_basis_eval(x, degree, knots));
    return rcpp_result_gen;
END_RCPP
}
// tensor_basis
arma::vec tensor_basis(const arma::mat& X, const List& knots_list, const arma::ivec& degrees, const arma::ivec& var_idx, const unsigned int K);
RcppExport SEXP _mlabs_tensor_basis(SEXP XSEXP, SEXP knots_listSEXP, SEXP degreesSEXP, SEXP var_idxSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type knots_list(knots_listSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type var_idx(var_idxSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_basis(X, knots_list, degrees, var_idx, K));
    return rcpp_result_gen;
END_RCPP
}
// build_design_matrix
arma::mat build_design_matrix(const arma::mat& X, const List& xi_list, const List& C_list, const List& nu_list, const arma::ivec& K_vec, const unsigned int J);
RcppExport SEXP _mlabs_build_design_matrix(SEXP XSEXP, SEXP xi_listSEXP, SEXP C_listSEXP, SEXP nu_listSEXP, SEXP K_vecSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type xi_list(xi_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type nu_list(nu_listSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(build_design_matrix(X, xi_list, C_list, nu_list, K_vec, J));
    return rcpp_result_gen;
END_RCPP
}
// compute_boundary
arma::mat compute_boundary(const arma::mat& X, const double prop);
RcppExport SEXP _mlabs_compute_boundary(SEXP XSEXP, SEXP propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type prop(propSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_boundary(X, prop));
    return rcpp_result_gen;
END_RCPP
}
// generate_knots_weighted
arma::vec generate_knots_weighted(const arma::vec& x, const arma::vec& bd, const arma::vec& resid, const unsigned int degree, const bool use_residual, const double temperature, const double knot_window_frac, const double odd_anchor_uniform);
RcppExport SEXP _mlabs_generate_knots_weighted(SEXP xSEXP, SEXP bdSEXP, SEXP residSEXP, SEXP degreeSEXP, SEXP use_residualSEXP, SEXP temperatureSEXP, SEXP knot_window_fracSEXP, SEXP odd_anchor_uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type resid(residSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_residual(use_residualSEXP);
    Rcpp::traits::input_parameter< const double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_window_frac(knot_window_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type odd_anchor_uniform(odd_anchor_uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_knots_weighted(x, bd, resid, degree, use_residual, temperature, knot_window_frac, odd_anchor_uniform));
    return rcpp_result_gen;
END_RCPP
}
// log_knot_proposal_density
double log_knot_proposal_density(const arma::vec& knots, const arma::vec& x, const arma::vec& bd, const arma::vec& resid, const unsigned int degree, const bool use_residual, const double temperature, const double knot_window_frac, const double odd_anchor_uniform);
RcppExport SEXP _mlabs_log_knot_proposal_density(SEXP knotsSEXP, SEXP xSEXP, SEXP bdSEXP, SEXP residSEXP, SEXP degreeSEXP, SEXP use_residualSEXP, SEXP temperatureSEXP, SEXP knot_window_fracSEXP, SEXP odd_anchor_uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type resid(residSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_residual(use_residualSEXP);
    Rcpp::traits::input_parameter< const double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_window_frac(knot_window_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type odd_anchor_uniform(odd_anchor_uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(log_knot_proposal_density(knots, x, bd, resid, degree, use_residual, temperature, knot_window_frac, odd_anchor_uniform));
    return rcpp_result_gen;
END_RCPP
}
// compute_relevance
arma::vec compute_relevance(const arma::mat& X, const arma::vec& resid);
RcppExport SEXP _mlabs_compute_relevance(SEXP XSEXP, SEXP residSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type resid(residSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_relevance(X, resid));
    return rcpp_result_gen;
END_RCPP
}
// compute_relevance_ema
arma::vec compute_relevance_ema(const arma::mat& X, const arma::vec& resid, const arma::vec& rho_cache, const unsigned int iter, const unsigned int update_interval, const double decay);
RcppExport SEXP _mlabs_compute_relevance_ema(SEXP XSEXP, SEXP residSEXP, SEXP rho_cacheSEXP, SEXP iterSEXP, SEXP update_intervalSEXP, SEXP decaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type resid(residSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho_cache(rho_cacheSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type update_interval(update_intervalSEXP);
    Rcpp::traits::input_parameter< const double >::type decay(decaySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_relevance_ema(X, resid, rho_cache, iter, update_interval, decay));
    return rcpp_result_gen;
END_RCPP
}
// effective_var_probs
arma::vec effective_var_probs(const arma::vec& pi_var, const arma::vec& rho, const double boost);
RcppExport SEXP _mlabs_effective_var_probs(SEXP pi_varSEXP, SEXP rhoSEXP, SEXP boostSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pi_var(pi_varSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type boost(boostSEXP);
    rcpp_result_gen = Rcpp::wrap(effective_var_probs(pi_var, rho, boost));
    return rcpp_result_gen;
END_RCPP
}
// sample_variables
arma::ivec sample_variables(const arma::vec& probs, const unsigned int K, const bool replace);
RcppExport SEXP _mlabs_sample_variables(SEXP probsSEXP, SEXP KSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_variables(probs, K, replace));
    return rcpp_result_gen;
END_RCPP
}
// update_pi_mh_wor
arma::vec update_pi_mh_wor(const arma::vec& pi_cur, const List& nu_list, const arma::ivec& K_vec, const unsigned int J, const unsigned int p, const double alpha);
RcppExport SEXP _mlabs_update_pi_mh_wor(SEXP pi_curSEXP, SEXP nu_listSEXP, SEXP K_vecSEXP, SEXP JSEXP, SEXP pSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pi_cur(pi_curSEXP);
    Rcpp::traits::input_parameter< const List& >::type nu_list(nu_listSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pi_mh_wor(pi_cur, nu_list, K_vec, J, p, alpha));
    return rcpp_result_gen;
END_RCPP
}
// backfitting_update
List backfitting_update(const arma::vec& y, const arma::mat& X, arma::vec beta, arma::mat Bmat, List C_list, List xi_list, List nu_list, arma::ivec K_vec, unsigned int J, const double beta0, const double sigmay, const double sigmab, const arma::mat& bd, const unsigned int n, const arma::ivec& allowed_degrees, const double xi_step_size, const double knot_temperature, const unsigned int n_refresh, const double knot_window_frac, const double odd_anchor_uniform);
RcppExport SEXP _mlabs_backfitting_update(SEXP ySEXP, SEXP XSEXP, SEXP betaSEXP, SEXP BmatSEXP, SEXP C_listSEXP, SEXP xi_listSEXP, SEXP nu_listSEXP, SEXP K_vecSEXP, SEXP JSEXP, SEXP beta0SEXP, SEXP sigmaySEXP, SEXP sigmabSEXP, SEXP bdSEXP, SEXP nSEXP, SEXP allowed_degreesSEXP, SEXP xi_step_sizeSEXP, SEXP knot_temperatureSEXP, SEXP n_refreshSEXP, SEXP knot_window_fracSEXP, SEXP odd_anchor_uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bmat(BmatSEXP);
    Rcpp::traits::input_parameter< List >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< List >::type xi_list(xi_listSEXP);
    Rcpp::traits::input_parameter< List >::type nu_list(nu_listSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const double >::type sigmay(sigmaySEXP);
    Rcpp::traits::input_parameter< const double >::type sigmab(sigmabSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type allowed_degrees(allowed_degreesSEXP);
    Rcpp::traits::input_parameter< const double >::type xi_step_size(xi_step_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_temperature(knot_temperatureSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_refresh(n_refreshSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_window_frac(knot_window_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type odd_anchor_uniform(odd_anchor_uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(backfitting_update(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, beta0, sigmay, sigmab, bd, n, allowed_degrees, xi_step_size, knot_temperature, n_refresh, knot_window_frac, odd_anchor_uniform));
    return rcpp_result_gen;
END_RCPP
}
// update_sigmay
double update_sigmay(const arma::vec& y, const arma::vec& beta, const arma::mat& Bmat, const double beta0, const double sigr, const double sigR);
RcppExport SEXP _mlabs_update_sigmay(SEXP ySEXP, SEXP betaSEXP, SEXP BmatSEXP, SEXP beta0SEXP, SEXP sigrSEXP, SEXP sigRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bmat(BmatSEXP);
    Rcpp::traits::input_parameter< const double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const double >::type sigr(sigrSEXP);
    Rcpp::traits::input_parameter< const double >::type sigR(sigRSEXP);
    rcpp_result_gen = Rcpp::wrap(update_sigmay(y, beta, Bmat, beta0, sigr, sigR));
    return rcpp_result_gen;
END_RCPP
}
// birth_step_collapsed
List birth_step_collapsed(const arma::vec& y, const arma::mat& X, arma::vec beta, arma::mat Bmat, List C_list, List xi_list, List nu_list, arma::ivec K_vec, unsigned int J, const double M, const double beta0, const double sigmay, const double sigmab, const arma::mat& bd, const unsigned int maxInter, const unsigned int n, const unsigned int p, const arma::vec& jump_prob, const arma::vec& pi_var, const arma::ivec& allowed_degrees, const double knot_temperature, const arma::vec& rho_cache, const unsigned int iter, const unsigned int rho_update_interval, const double boost, const double ref_sigma, const unsigned int NB_max, const double lambda_J, const arma::vec& k_weights, const double knot_window_frac, const double odd_anchor_uniform);
RcppExport SEXP _mlabs_birth_step_collapsed(SEXP ySEXP, SEXP XSEXP, SEXP betaSEXP, SEXP BmatSEXP, SEXP C_listSEXP, SEXP xi_listSEXP, SEXP nu_listSEXP, SEXP K_vecSEXP, SEXP JSEXP, SEXP MSEXP, SEXP beta0SEXP, SEXP sigmaySEXP, SEXP sigmabSEXP, SEXP bdSEXP, SEXP maxInterSEXP, SEXP nSEXP, SEXP pSEXP, SEXP jump_probSEXP, SEXP pi_varSEXP, SEXP allowed_degreesSEXP, SEXP knot_temperatureSEXP, SEXP rho_cacheSEXP, SEXP iterSEXP, SEXP rho_update_intervalSEXP, SEXP boostSEXP, SEXP ref_sigmaSEXP, SEXP NB_maxSEXP, SEXP lambda_JSEXP, SEXP k_weightsSEXP, SEXP knot_window_fracSEXP, SEXP odd_anchor_uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bmat(BmatSEXP);
    Rcpp::traits::input_parameter< List >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< List >::type xi_list(xi_listSEXP);
    Rcpp::traits::input_parameter< List >::type nu_list(nu_listSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const double >::type sigmay(sigmaySEXP);
    Rcpp::traits::input_parameter< const double >::type sigmab(sigmabSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type maxInter(maxInterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jump_prob(jump_probSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pi_var(pi_varSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type allowed_degrees(allowed_degreesSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_temperature(knot_temperatureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho_cache(rho_cacheSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type rho_update_interval(rho_update_intervalSEXP);
    Rcpp::traits::input_parameter< const double >::type boost(boostSEXP);
    Rcpp::traits::input_parameter< const double >::type ref_sigma(ref_sigmaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NB_max(NB_maxSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_J(lambda_JSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type k_weights(k_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_window_frac(knot_window_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type odd_anchor_uniform(odd_anchor_uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(birth_step_collapsed(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, maxInter, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature, rho_cache, iter, rho_update_interval, boost, ref_sigma, NB_max, lambda_J, k_weights, knot_window_frac, odd_anchor_uniform));
    return rcpp_result_gen;
END_RCPP
}
// death_step_collapsed
List death_step_collapsed(const arma::vec& y, const arma::mat& X, arma::vec beta, arma::mat Bmat, List C_list, List xi_list, List nu_list, arma::ivec K_vec, unsigned int J, const double M, const double beta0, const double sigmay, const double sigmab, const arma::mat& bd, const unsigned int n, const unsigned int p, const arma::vec& jump_prob, const arma::vec& pi_var, const arma::ivec& allowed_degrees, const double knot_temperature, const arma::vec& rho_cache, const unsigned int iter, const unsigned int rho_update_interval, const double boost, const double ref_sigma, const unsigned int NB_max, const double lambda_J, const double knot_window_frac, const double odd_anchor_uniform);
RcppExport SEXP _mlabs_death_step_collapsed(SEXP ySEXP, SEXP XSEXP, SEXP betaSEXP, SEXP BmatSEXP, SEXP C_listSEXP, SEXP xi_listSEXP, SEXP nu_listSEXP, SEXP K_vecSEXP, SEXP JSEXP, SEXP MSEXP, SEXP beta0SEXP, SEXP sigmaySEXP, SEXP sigmabSEXP, SEXP bdSEXP, SEXP nSEXP, SEXP pSEXP, SEXP jump_probSEXP, SEXP pi_varSEXP, SEXP allowed_degreesSEXP, SEXP knot_temperatureSEXP, SEXP rho_cacheSEXP, SEXP iterSEXP, SEXP rho_update_intervalSEXP, SEXP boostSEXP, SEXP ref_sigmaSEXP, SEXP NB_maxSEXP, SEXP lambda_JSEXP, SEXP knot_window_fracSEXP, SEXP odd_anchor_uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bmat(BmatSEXP);
    Rcpp::traits::input_parameter< List >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< List >::type xi_list(xi_listSEXP);
    Rcpp::traits::input_parameter< List >::type nu_list(nu_listSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const double >::type sigmay(sigmaySEXP);
    Rcpp::traits::input_parameter< const double >::type sigmab(sigmabSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jump_prob(jump_probSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pi_var(pi_varSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type allowed_degrees(allowed_degreesSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_temperature(knot_temperatureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho_cache(rho_cacheSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type rho_update_interval(rho_update_intervalSEXP);
    Rcpp::traits::input_parameter< const double >::type boost(boostSEXP);
    Rcpp::traits::input_parameter< const double >::type ref_sigma(ref_sigmaSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NB_max(NB_maxSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_J(lambda_JSEXP);
    Rcpp::traits::input_parameter< const double >::type knot_window_frac(knot_window_fracSEXP);
    Rcpp::traits::input_parameter< const double >::type odd_anchor_uniform(odd_anchor_uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(death_step_collapsed(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature, rho_cache, iter, rho_update_interval, boost, ref_sigma, NB_max, lambda_J, knot_window_frac, odd_anchor_uniform));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlabs_B_basis_eval", (DL_FUNC) &_mlabs_B_basis_eval, 3},
    {"_mlabs_tensor_basis", (DL_FUNC) &_mlabs_tensor_basis, 5},
    {"_mlabs_build_design_matrix", (DL_FUNC) &_mlabs_build_design_matrix, 6},
    {"_mlabs_compute_boundary", (DL_FUNC) &_mlabs_compute_boundary, 2},
    {"_mlabs_generate_knots_weighted", (DL_FUNC) &_mlabs_generate_knots_weighted, 8},
    {"_mlabs_log_knot_proposal_density", (DL_FUNC) &_mlabs_log_knot_proposal_density, 9},
    {"_mlabs_compute_relevance", (DL_FUNC) &_mlabs_compute_relevance, 2},
    {"_mlabs_compute_relevance_ema", (DL_FUNC) &_mlabs_compute_relevance_ema, 6},
    {"_mlabs_effective_var_probs", (DL_FUNC) &_mlabs_effective_var_probs, 3},
    {"_mlabs_sample_variables", (DL_FUNC) &_mlabs_sample_variables, 3},
    {"_mlabs_update_pi_mh_wor", (DL_FUNC) &_mlabs_update_pi_mh_wor, 6},
    {"_mlabs_backfitting_update", (DL_FUNC) &_mlabs_backfitting_update, 20},
    {"_mlabs_update_sigmay", (DL_FUNC) &_mlabs_update_sigmay, 6},
    {"_mlabs_birth_step_collapsed", (DL_FUNC) &_mlabs_birth_step_collapsed, 31},
    {"_mlabs_death_step_collapsed", (DL_FUNC) &_mlabs_death_step_collapsed, 29},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlabs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
