# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

B_basis_eval <- function(x, degree, knots) {
    .Call(`_mlabs_B_basis_eval`, x, degree, knots)
}

tensor_basis <- function(X, knots_list, degrees, var_idx, K) {
    .Call(`_mlabs_tensor_basis`, X, knots_list, degrees, var_idx, K)
}

build_design_matrix <- function(X, xi_list, C_list, nu_list, K_vec, J) {
    .Call(`_mlabs_build_design_matrix`, X, xi_list, C_list, nu_list, K_vec, J)
}

compute_boundary <- function(X, prop) {
    .Call(`_mlabs_compute_boundary`, X, prop)
}

generate_knots_weighted <- function(x, bd, resid, degree, use_residual, temperature = 1.0, knot_window_frac = 0.01, odd_anchor_uniform = 0.05) {
    .Call(`_mlabs_generate_knots_weighted`, x, bd, resid, degree, use_residual, temperature, knot_window_frac, odd_anchor_uniform)
}

log_knot_proposal_density <- function(knots, x, bd, resid, degree, use_residual, temperature = 1.0, knot_window_frac = 0.01, odd_anchor_uniform = 0.05) {
    .Call(`_mlabs_log_knot_proposal_density`, knots, x, bd, resid, degree, use_residual, temperature, knot_window_frac, odd_anchor_uniform)
}

compute_relevance <- function(X, resid) {
    .Call(`_mlabs_compute_relevance`, X, resid)
}

compute_relevance_ema <- function(X, resid, rho_cache, iter, update_interval = 10L, decay = 0.9) {
    .Call(`_mlabs_compute_relevance_ema`, X, resid, rho_cache, iter, update_interval, decay)
}

effective_var_probs <- function(pi_var, rho, boost = 5.0) {
    .Call(`_mlabs_effective_var_probs`, pi_var, rho, boost)
}

sample_variables <- function(probs, K, replace) {
    .Call(`_mlabs_sample_variables`, probs, K, replace)
}

update_pi_mh_wor <- function(pi_cur, nu_list, K_vec, J, p, alpha) {
    .Call(`_mlabs_update_pi_mh_wor`, pi_cur, nu_list, K_vec, J, p, alpha)
}

backfitting_update <- function(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, beta0, sigmay, sigmab, bd, n, allowed_degrees, xi_step_size = 0.05, knot_temperature = 1.0, n_refresh = 0L, knot_window_frac = 0.001, odd_anchor_uniform = 0.05) {
    .Call(`_mlabs_backfitting_update`, y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, beta0, sigmay, sigmab, bd, n, allowed_degrees, xi_step_size, knot_temperature, n_refresh, knot_window_frac, odd_anchor_uniform)
}

update_sigmay <- function(y, beta, Bmat, beta0, sigr, sigR) {
    .Call(`_mlabs_update_sigmay`, y, beta, Bmat, beta0, sigr, sigR)
}

birth_step_collapsed <- function(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, maxInter, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature = 1.0, rho_cache, iter = 0L, rho_update_interval = 10L, boost = 5.0, ref_sigma = 1.0, NB_max = 100L, lambda_J = 0.0, k_weights, knot_window_frac = 0.001, odd_anchor_uniform = 0.05) {
    .Call(`_mlabs_birth_step_collapsed`, y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, maxInter, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature, rho_cache, iter, rho_update_interval, boost, ref_sigma, NB_max, lambda_J, k_weights, knot_window_frac, odd_anchor_uniform)
}

death_step_collapsed <- function(y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature = 1.0, rho_cache, iter = 0L, rho_update_interval = 10L, boost = 5.0, ref_sigma = 1.0, NB_max = 100L, lambda_J = 0.0, knot_window_frac = 0.001, odd_anchor_uniform = 0.05) {
    .Call(`_mlabs_death_step_collapsed`, y, X, beta, Bmat, C_list, xi_list, nu_list, K_vec, J, M, beta0, sigmay, sigmab, bd, n, p, jump_prob, pi_var, allowed_degrees, knot_temperature, rho_cache, iter, rho_update_interval, boost, ref_sigma, NB_max, lambda_J, knot_window_frac, odd_anchor_uniform)
}

